config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
      @products = Product.all
    end
		
		def new
			@product = Product.new
		end
		
		def create
			@product = Product.new(product_params)
			if @product.save
				redirect_to products_path, notice: "El producto fue publicado con exito"
			else
				render :new
			end
		end
		
		def show
			@product = Product.find(params[:id]) #este id se refiere al de la ruta /:id
		end
    
    private
		def product_params	
		params.require(:product).permit(:name, :url, :description)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Producthunt2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
			
			<h2>Productos</h2>
            <div class="text-right my-2">
				<%= link_to "Publicar Producto", new_product_path, class: "btn btn-primary" %>
			</div>

            <table class="table">
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>URL</th>
                    <th>Descripción</th>
                </tr>
                <% @products.each do |product| %>
                <tr>
                    <td><%= product.id %></td>
                    <td><%= product.name %></td>
                    <td><%= product.url %></td>
                    <td><%= product.description %></td>
                </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/products/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <h1>Publicar producto</h1>
            <%= form_for @product do |f| %>
                <div class="form-group">
                    <%= f.text_field :name, class: "form-control", placeholder:"Ingresa el nombre del producto" %>
                </div>
                <div class="form-group">
    				<%= f.url_field :url, class: "form-control", placeholder: "Ingresa la Url del producto"%>
				</div>
				<div class="form-group">
    				<%= f.text_area :description, class: "form-control", placeholder: "Ingresa la descripción del producto"%>
				</div>

				<div class="form-group">
    				<%= f.submit "Publicar producto", class: "btn btn-primary btn-block" %>
				</div>
				
            <% end %>
        </div>
    </div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h1><%= @product.name %></h1> 
			<p><%= @product.description %></p>
			<a href="<%= @product.url %>" target="_blank">Obtenlo!</a>
		</div>
	</div>
</div>